# Generated by Django 5.0.4 on 2024-05-03 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('image', models.ImageField(default='none.png', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=128)),
                ('photo', models.ImageField(default='none.png', upload_to='images/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=255, verbose_name='Answer Text')),
                ('is_correct', models.BooleanField(default=False)),
                ('image', models.ImageField(default='none.png', upload_to='images/')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='subjects.questions')),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(default='New test', max_length=255)),
                ('test_duration_minutes', models.TimeField(default='00:00:00')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.questions')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.tests')),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=128)),
                ('image', models.ImageField(default='none.png', upload_to='images/')),
                ('description', models.TextField()),
                ('question_type', models.IntegerField(choices=[(0, 'EASY'), (1, 'MIDDLE'), (2, 'HARD'), (3, 'Advanced')], default=0, verbose_name='Difficulty')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subjects')),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.topics'),
        ),
    ]
