# Generated by Django 5.0.4 on 2024-05-10 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_alter_answer_id_alter_question_id_alter_subject_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=models.ImageField(default='none.png', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(default='none.png', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='photo',
            field=models.ImageField(default='none.png', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(default='none.png', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='question_type',
            field=models.CharField(choices=[('EASY', 'EASY'), ('MIDDLE', 'MIDDLE'), ('HARD', 'HARD'), ('ADVANCED', 'Advanced')], default='EASY', max_length=20, verbose_name='Difficulty'),
        ),
        migrations.CreateModel(
            name='ResultAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_correct', models.BooleanField(default=False)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.question')),
                ('result_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.result')),
            ],
        ),
        migrations.DeleteModel(
            name='ResultAnswers',
        ),
    ]
