# Generated by Django 5.0.4 on 2024-05-10 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_alter_answer_image_alter_question_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultAnswers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_correct', models.BooleanField(default=False)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.question')),
                ('result_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.result')),
            ],
        ),
        migrations.DeleteModel(
            name='ResultAnswer',
        ),
    ]
