# Generated by Django 5.0.4 on 2024-05-10 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_resultanswers_delete_resultanswer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResultAnswers',
            new_name='ResultAnswer',
        ),
    ]
